name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
 
      - name: Run a one-line script
        run: echo Hello, Pulkit!

      - name: Run a multi-line script
        run: |
          echo test, and deploy your project.
